### ISSUE TITLE
Consumer Key

### ISSUE THREAD

**Issue by Benjemaa** [UrielCh/ovh-java-sdk#5]
I am using this api 0.9.3 , I tried dto create new ApiOVHCOnfig , anonymous class , after that I tried to get a service from OVH it says that Consumer Key is null , so I searched a little bit and I found that in APIOVHCORE uses another consumer KEy wich is initialised to null and there is no method to change it to a custom Consumer Key , you may see that and Reply to me How can I work with it ! 
Sorry for my bad English , I am just not focusing on my word after a long day working around the same error , And I am like 88% sure the Api is missing something ! thank you

**Comment by Benjemaa** [comment]
Well this issue is faced when we don't have usename/password , You should give access to those who have only the 3 keys !
Another thing there is an error on enumeration "Can not deserialize value of type net.minidev.ovh.api.vps.OvhVpsVersionEnum from String "2017v2":" it appears that you didn't implement all possible values of version Enum for Vps Model , thx

**Comment by UrielCh** [comment]
the API had been update since.
