### ISSUE TITLE
Issue object mapping

### ISSUE THREAD

**Issue by saschaarthur** [UrielCh/ovh-java-sdk#7]
maven include
```
		<dependency>
			<groupId>net.minidev</groupId>
			<artifactId>ovh-java-sdk-cloud</artifactId>
			<version>1.0.17</version>
		</dependency>
```

Stack: 
```
Exception:net.minidev.ovh.core.OvhServiceException: local conversion Error to net.minidev.ovh.api.ApiOvhCloud$2@2287bb65


net.minidev.ovh.core.ApiOvhUtils.convertTo(ApiOvhUtils.java:46)
net.minidev.ovh.core.ApiOvhBase.convertTo(ApiOvhBase.java:94)
net.minidev.ovh.api.ApiOvhCloud.project_GET(ApiOvhCloud.java:2564)
```

i think its caused by 2factor ovh login (if it fails), if you need more let me know

**Comment by UrielCh** [comment]
I am migrating all my java development to TypeScript.

Maintaining/updating this API in java involve random breaking change.

If you can, try to use my new API:
https://github.com/UrielCh/api-ovh-node

**Comment by saschaarthur** [comment]
dont get why switching the programming language should solve this..

**Comment by UrielCh** [comment]
I'm waiting for a `named parameter` feature in java to resume the java wrapper.

Each API update break the previous version.

I have have used java since 2003, too much java.
